### ISSUE TITLE
Java

### ISSUE THREAD

**Issue by HanzoDev1375** [RohitKushvaha01/FileTree#1]
Can it be used with Java?

**Comment by RohitKushvaha01** [comment]
> Can it be used with Java?

Yes

**Comment by HanzoDev1375** [comment]
tnks

**Comment by HanzoDev1375** [comment]
@RohitKushvaha01  jitpack not work not download your library

**Comment by RohitKushvaha01** [comment]
> @RohitKushvaha01  jitpack not work not download your library

What version are you using?  What is the error? Have you added the jitpack.io repository to your settings.gradle file?

**Comment by HanzoDev1375** [comment]
I did everything step by step, but it won't download. Do you know that
jetpack has stopped working?

در تاریخ چهارشنبه 30 اکتبر 2024، 16:30 Rohit Kushvaha <
***@***.***> نوشت:
